TRUNCATE TABLE dvde_stg_accounts RESTART IDENTITY CASCADE;
TRUNCATE TABLE dvde_stg_passport_blacklist RESTART IDENTITY CASCADE;
TRUNCATE TABLE dvde_stg_cards RESTART IDENTITY CASCADE;
TRUNCATE TABLE dvde_stg_clients RESTART IDENTITY CASCADE;
TRUNCATE TABLE dvde_stg_terminals RESTART IDENTITY CASCADE;
TRUNCATE TABLE dvde_stg_transactions RESTART IDENTITY CASCADE;