TRUNCATE TABLE stg_accounts RESTART IDENTITY CASCADE;
TRUNCATE TABLE stg_passport_blacklist RESTART IDENTITY CASCADE;
TRUNCATE TABLE stg_cards RESTART IDENTITY CASCADE;
TRUNCATE TABLE stg_clients RESTART IDENTITY CASCADE;
TRUNCATE TABLE stg_terminals RESTART IDENTITY CASCADE;
TRUNCATE TABLE stg_transactions RESTART IDENTITY CASCADE;